---
abstract: 'Perl core essentials in a single import'
author:
  - 'Ali Anari <ali@anari.me>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Modern: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Core
requires:
  PerlX::Define: '0'
  PerlX::Maybe: '0'
  Sub::Infix: '0'
  Syntax::Feature::Try: '0'
  constant: '0'
  feature: '0'
  match::simple: '0'
  mro: '0'
  perl: 5.010_000
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/aanari/Perl-Core/issues
  repository: git://github.com/aanari/Perl-Core.git
version: '0.0100'
